### PR TITLE
Add French

### PR DESCRIPTION
**Pull request by JordanDIG**
[#12 ](https://github.com/allotropia/nextcloud_files_libreoffice_edit/issues/12) Add French

### CODE REVIEW

**Comment by JordanDIG** [comment]
@smehrbrodt Can you merge it ?

**Comment by smehrbrodt** [comment]
Are you sure this works?
JSON files can't contain Javascript.

**Comment by JordanDIG** [comment]
OOOPS yes I will correct this

**Review by JordanDIG — COMMENTED** [review]
{ "translations": {
    "Edit with LibreOffice" : "Éditer avec LibreOffice"
},"pluralForm" :"nplurals=2; plural=(n != 1);"
}

**Comment by JordanDIG** [comment]
I can't review my code.. @smehrbrodt

**Comment by smehrbrodt** [comment]
You can just push more commits to your branch to update the PR.
Why did you close it btw?

**Comment by JordanDIG** [comment]
Unfortunately I didn't succeed, so I created a new pull request

**Pull request closed without merging**
